name: Secret scanning

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scan-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Run script
        run: |
          echo "What follows is known as the 'Song of the Count'"
          echo << !!!
          You know that I am called the Count
          Because I really love to count
          Sometimes I sit and count all day,
          But sometimes I get carried away
          
          I count slowly, slowly, slowly, getting faster
          Once I start in counting it's really hard to stop
          Faster, faster, it is so exciting.
          I could count forever, count until I drop
          
          One, two, three, four,
          One-two-three-four, one, two,
          I love counting, whatever the amount.
          
          One, two, three, four, hey, ey, ey, ey, hey, ey, ey, ey,
          One, two, three, four, one, two, that's the song of the Count.
          
          I count the spiders on the wall.
          I count the cobwebs in the hall.
          I count the candles on the shelf.
          When I'm alone, I count myself.
          
          I count slowly, slowly, slowly getting faster
          Once I start in counting, it's very hard to stop
          Faster, faster, it is so exciting.
          I could count forever, count until I drop
          
          One, two, three, four,
          One-two-three-four, one, two, three, four, one, two,
          I love counting, whatever the amount.
          
          One, two, three, four, hey, ey, ey, ey, hey, ey, ey, ey,
          One, two, three, four, one, two, that's the song of the Count. Hey!
          !!!
